add mint_nft script
Web3Mustketeers/taskmon.ai pull request #13
Opened 2023-07-05 08:48 UTC by kozayupapa

mint nft to solana on chain script.

minted NFT example:
 https://explorer.solana.com/address/4NTVmi1uu951XCEUkmqiM7Gc3kBVU1JQavJHTN4xPxnB?cluster=devnet

2023-07-05 09:03 UTC, Nasfame requested changes

2023-07-05 09:03 UTC, Nasfame commented on Sandbox/Solana/src/mint_nft.ts
> +import secret = require('/Users/takehararyuuji/ryu-solana-wallet/my-keypair.json');
Can u store the path as environment variable? Also we are more or like going to deploy on Ubuntu so let's remove windows paths and use relative paths...

2023-07-05 09:04 UTC, Nasfame commented on Sandbox/Solana/tsconfig.json
> +    "module": "commonjs",
Use es6 modules...

2023-07-05 09:04 UTC, Nasfame commented on Sandbox/Solana/tsconfig.json
> +    "target": "es2017",
Use es2022

2023-07-05 09:05 UTC, Nasfame commented on Sandbox/Solana/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Remove lock files. Add it to gitignore

2023-07-06 11:52 UTC, kozayupapa commented on Sandbox/Solana/tsconfig.json
> +    "module": "commonjs",
applied

2023-07-06 11:52 UTC, kozayupapa commented on Sandbox/Solana/tsconfig.json
> +    "target": "es2017",
applied

2023-07-06 11:53 UTC, kozayupapa commented on Sandbox/Solana/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
I think we should include lock file to github to fix versions of each module.
why do you think remove lock file?

2023-07-06 12:02 UTC, Nasfame commented on Sandbox/Solana/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package.json locks the versions

2023-07-06 12:02 UTC, Nasfame commented on Sandbox/Solana/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
lock files create git log noise. Its better to have it removed

2023-07-06 12:05 UTC, Nasfame commented on Sandbox/Solana/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
if there a transitive deps conflicts, then okay you can use yarn

2023-07-06 12:08 UTC, Nasfame approved these changes
LGTM

2023-07-06 12:09 UTC, merged